#!/usr/bin/env python3
"""
02convertMetadata.py

Convert the raw mzML file list CSV (generated by 01createMetadata.py)
into a structured metadata CSV with columns:
  batch_id, file_name, mode, MS_level, drug_id, replicate_id, drug_concentration

Usage:
    python 02convertMetadata.py <input_csv> <batch_id>

Example:
    python 02convertMetadata.py mzml_file_list_Batch1.csv Batch1
"""

import os
import re
import sys
import pandas as pd


def parse_filename(filename: str) -> dict:
    """
    Parse a single .mzML filename and return a dict of metadata fields.

    Supported patterns:
      - {drug_id}_{replicate_id}_{H|L}.mzML   (e.g. 10_1_H.mzML)
      - QCMSMS_{N}.mzML                        (e.g. QCMSMS_20.mzML)
      - QC_{N}.mzML                            (e.g. QC_1.mzML)
      - CT{N}_{R}.mzML                         (e.g. CT1_1.mzML)
    """
    name = filename.strip()
    if not name.lower().endswith('.mzml'):
        return None

    # Remove .mzML extension for parsing
    stem = name[:-5]  # remove '.mzML' (5 chars)

    # Default fields
    info = {
        'file_name': name,
        'mode': 'negitive',
        'MS_level': 'MS',
        'drug_id': '',
        'replicate_id': '',
        'drug_concentration': '',
    }

    # Pattern 1: QCMSMS_{N}.mzML
    m = re.match(r'^QCMSMS_(\d+)$', stem)
    if m:
        info['MS_level'] = 'MSMS'
        info['drug_id'] = 'QCMSMS'
        info['replicate_id'] = m.group(1)
        return info

    # Pattern 2: QC_{N}.mzML
    m = re.match(r'^QC_(\d+)$', stem)
    if m:
        info['drug_id'] = 'QC'
        info['replicate_id'] = m.group(1)
        return info

    # Pattern 3: CT{N}_{R}.mzML  (e.g. CT1_1, CT1_2)
    m = re.match(r'^(CT\d+)_(\d+)$', stem)
    if m:
        info['drug_id'] = m.group(1)
        info['replicate_id'] = m.group(2)
        return info

    # Pattern 4: {drug_id}_{replicate_id}_{H|L}.mzML  (e.g. 10_1_H, 1_1_L)
    m = re.match(r'^(\d+)_(\d+)_([HL])$', stem)
    if m:
        drug_id = m.group(1)
        replicate_id = m.group(2)
        conc_level = m.group(3)
        info['drug_id'] = drug_id
        info['replicate_id'] = replicate_id
        info['drug_concentration'] = 'High' if conc_level == 'H' else 'Low'
        return info

    # If nothing matched, warn and skip
    print(f"Warning: unrecognized filename pattern '{name}', skipping", file=sys.stderr)
    return None


def main():
    if len(sys.argv) < 3:
        print("Usage: python 02convertMetadata.py <input_csv> <batch_id>", file=sys.stderr)
        sys.exit(1)

    input_csv = sys.argv[1]
    batch_id_arg = sys.argv[2]

    # Extract numeric batch ID from e.g. "Batch1" -> 1
    m = re.search(r'(\d+)$', batch_id_arg)
    batch_id = int(m.group(1)) if m else batch_id_arg

    # Read input CSV
    df = pd.read_csv(input_csv)

    # Determine the column name; could be 'file_name' or the first column
    if 'file_name' in df.columns:
        files = df['file_name']
    else:
        files = df.iloc[:, 0]  # use first column

    records = []
    for fname in files:
        fname_str = str(fname).strip()
        if not fname_str:
            continue
        parsed = parse_filename(fname_str)
        if parsed is None:
            continue
        parsed['batch_id'] = batch_id
        records.append(parsed)

    if not records:
        print("Error: no valid records parsed from input file", file=sys.stderr)
        sys.exit(1)

    out_df = pd.DataFrame(records)

    # Reorder columns as desired
    column_order = ['batch_id', 'file_name', 'mode', 'MS_level',
                    'drug_id', 'replicate_id', 'drug_concentration']
    out_df = out_df[column_order]

    # Build output filename: mzml_file_list_Batch1_convert.csv
    input_basename = os.path.splitext(os.path.basename(input_csv))[0]
    output_csv = os.path.join(
        os.path.dirname(input_csv) or '.',
        f"{input_basename}_convert.csv"
    )

    out_df.to_csv(output_csv, index=False)
    print(f"Converted metadata written to: {output_csv}")


if __name__ == '__main__':
    main()